---
- name: Play to configure server
  hosts: localhost
  any_errors_fatal: true
  gather_facts: false
  become: true

  tasks:

    - include: playbooks/apache2/main.yml
    - include: playbooks/php/main.yml

# Pause for 10 second     
    - name: Pause playbook for configure to install
      pause:
        seconds: 10
